Controllers/DecryptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AnotherTechblog.Models;
using Microsoft.AspNetCore.Mvc;

namespace AnotherTechblog.Controllers
{
    public class DecryptionController : Controller
    {
        // GET: /<controller>/
        public IActionResult DecryptCipher()
        {
            var model = new DecryptCipherViewModel();
            ViewBag.Title = "Decrypt Cipher";
            return View(model);
        }

        [HttpPost]
        public IActionResult DecryptCipher(DecryptCipherViewModel model)
        {
            switch (model.Algorithm)
            {
                case "Caesar":
                    model.DecryptedCipher = DecryptCaesarCipher(model.Cipher);
                    break;

                case "Vigenere":
                    model.DecryptedCipher = DecryptVigenereCipher(model.Cipher, "KEY");
                    break;

                case "RailFence":
                    model.DecryptedCipher = DecryptRailFenceCipher(model.Cipher, 3);
                    break;

                default:
                    break;  
            }

            ViewBag.Title = "Decrypt Cipher";

            return View(model);
        }

        private string DecryptCaesarCipher(string cipher)
        {
            string decryptedCipher = "";

            for (int shift = 1; shift <= 25; shift++)
            {
                decryptedCipher += "<strong>Shift " + shift + ": </strong>";

                foreach (char c in cipher)
                {
                    if (char.IsLetter(c))
                    {
                        char baseChar = char.IsUpper(c) ? 'A' : 'a';
                        char decryptedChar = (char)((((c - baseChar) - shift + 26) % 26) + baseChar);
                        decryptedCipher += decryptedChar;
                    }
                    else
                    {
                        decryptedCipher += c;
                    }
                }

                decryptedCipher += "<br>";
            }

            return decryptedCipher;
        }


        private string DecryptVigenereCipher(string cipher, string key)
        {
            string decryptedCipher = "";
            int keyIndex = 0;

            foreach (char c in cipher)
            {
                if (char.IsLetter(c))
                {
                    int cipherIndex = char.ToUpper(c) - 65;
                    int keyChar = char.ToUpper(key[keyIndex % key.Length]) - 65;
                    int decryptedIndex = (cipherIndex - keyChar + 26) % 26;
                    char decryptedChar = (char)(decryptedIndex + 65);
                    decryptedCipher += decryptedChar;

                    keyIndex++;
                }
                else
                {
                    decryptedCipher += c;
                }
            }

            return decryptedCipher;
        }

        private string DecryptRailFenceCipher(string cipher, int rails)
        {
            int cipherLength = cipher.Length;
            int fullCycleLength = rails * 2 - 2;

            string decryptedCipher = "";

            for (int i = 0; i < cipherLength; i += fullCycleLength)
            {
                decryptedCipher += cipher[i];
            }

            for (int r = 1; r < rails - 1; r++)
            {
                for (int i = r; i < cipherLength; i += fullCycleLength)
                {
                    decryptedCipher += cipher[i];

                    int secondIndex = i + (fullCycleLength - r * 2);

                    if (secondIndex < cipherLength)
                    {
                        decryptedCipher += cipher[secondIndex];
                    }
                }
            }

            for (int i = rails - 1; i < cipherLength; i += fullCycleLength)
            {
                decryptedCipher += cipher[i];
            }

            return decryptedCipher;
        }
    }
}

Controllers/EncryptionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AnotherTechblog.Models;
using System.Text;
using System.Security.Cryptography;

namespace AnotherTechblog.Controllers
{
    public class EncryptionController : Controller
    {
        private readonly EncryptionCipherViewModel _model = new EncryptionCipherViewModel();

        public EncryptionController()
        {
            _model.PlainText = "";
        }
        public IActionResult EncryptCipher()
        {
            var model = new EncryptionCipherViewModel();
            return View(model);
        }

        [HttpPost]
        public IActionResult EncryptCipher(EncryptionCipherViewModel model)
        {
            model.Algorithm = Request.Form["algorithm"].ToString();

            switch (model.Algorithm)
            {
                case "caesar":
                    model.Cipher = EncryptCaesarCipher(model.PlainText, 3);
                    break;

                case "vigenere":
                    model.Cipher = EncryptVigenereCipher(model.PlainText, "KEY");
                    break;

                case "railfence":
                    model.Cipher = EncryptRailFenceCipher(model.PlainText, 3);
                    break;

                case "sha256":
                    model.Cipher = EncryptSha256Cipher(model.PlainText);
                    break;

                default:
                    break;
                
            }

            ViewBag.Title = "Encrypt Cipher";

            return View(model);
        }

        private string EncryptCaesarCipher(string plainText, int shift)
        {
            string cipherText = "";

            foreach (char c in plainText)
            {
                if (char.IsLetter(c))
                {
                    char cipherChar = (char)((((c - 65) + shift) % 26) + 65);
                    cipherText += cipherChar;
                }
                else
                {
                    cipherText += c;
                }
            }

            return cipherText;
        }

        private string EncryptVigenereCipher(string plainText, string key)
        {
            string cipherText = "";
            int keyIndex = 0;

            foreach (char c in plainText)
            {
                if (char.IsLetter(c))
                {
                    int plainIndex = char.ToUpper(c) - 65;
                    int keyChar = char.ToUpper(key[keyIndex % key.Length]) - 65;
                    int cipherIndex = (plainIndex + keyChar) % 26;
                    char cipherChar = (char)(cipherIndex + 65);
                    cipherText += cipherChar;

                    keyIndex++;
                }
                else
                {
                    cipherText += c;
                }
            }

            return cipherText;
        }

        private string EncryptRailFenceCipher(string plainText, int rails)
        {
            int plainTextLength = plainText.Length;
            int fullCycleLength = rails * 2 - 2;

            string cipherText = "";

            for (int i = 0; i < plainTextLength; i += fullCycleLength)
            {
                cipherText += plainText[i];
            }

            for (int r = 1; r < rails - 1; r++)
            {
                for (int i = r; i < plainTextLength; i += fullCycleLength)
                {
                    cipherText += plainText[i];

                    int secondIndex = i + (fullCycleLength - r * 2);

                    if (secondIndex < plainTextLength)
                    {
                        cipherText += plainText[secondIndex];
                    }
                }
            }

            for (int i = rails - 1; i < plainTextLength; i += fullCycleLength)
            {
                cipherText += plainText[i];
            }

            return cipherText;
        }

        private string EncryptSha256Cipher(string plainText)
        {
            using (SHA256 sha256Hash = SHA256.Create())
            {
                byte[] bytes = sha256Hash.ComputeHash(Encoding.UTF8.GetBytes(plainText));

                StringBuilder builder = new StringBuilder();
                for (int i = 0; i < bytes.Length; i++)
                {
                    builder.Append(bytes[i].ToString("x2"));
                }
                return builder.ToString();
            }
        }

    }
}

Controllers/MazeController.cs
using Microsoft.AspNetCore.Mvc;

namespace AnotherTechblog.Controllers
{
    public class MazeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/WordCountController.cs
using AnotherTechblog.Data;
using AnotherTechblog.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Text;
using System.Web;

namespace AnotherTechblog.Controllers
{
    public class WordCountController : Controller
    {
        private readonly HttpClient _client = new HttpClient();
        private readonly AnotherTechblogDbContext _context;

        public WordCountController(AnotherTechblogDbContext context)
        {
            _context = context ?? throw new ArgumentNullException(nameof(context));
            _client = new HttpClient();
        }

        public IActionResult WordCount()
        {
            var model = new WordCountViewModel();
            ViewBag.Title = "Wordcounter for Wikipedia Articles";
            return View(model);
        }

        public string StripPunctuation(string s)
        {
            var sb = new StringBuilder();
            foreach (char c in s)
            {
                if (!char.IsPunctuation(c))
                    sb.Append(c);
            }
            return sb.ToString();
        }

        [HttpPost]
        public async Task<IActionResult> WordCount(WordCountViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // Download article content
            var html = await _client.GetStringAsync(model.ArticleUrl);

            var htmlDoc = new HtmlAgilityPack.HtmlDocument();
            htmlDoc.LoadHtml(html);

            var articleNode = htmlDoc.DocumentNode.SelectSingleNode("//div[@id='mw-content-text']");
            var unwantedNodes = articleNode.SelectNodes("//script|//style|//table");
            if (unwantedNodes != null)
            {
                foreach (var unwantedNode in unwantedNodes)
                {
                    unwantedNode.Remove();
                }
            }

            var articleText = StripPunctuation(HttpUtility.HtmlDecode(articleNode.InnerText.Trim()));

            // Split article text into words
            var words = articleText.Split(' ');

            if (model.RemoveCommonWords)
            {
                words = FilterCommonWords(words).ToArray();
            }

            // Count occurrence of each word
            var wordCount = words.GroupBy(w => w.ToLower())
            .ToDictionary(g => g.Key, g => g.Count())
            .OrderByDescending(w => w.Value)
            .Take(15)
            .ToDictionary(x => x.Key, x => x.Value);

            // Save the top 15 words to the database
            foreach (var wc in wordCount)
            {
                var topWords = new WordCountResult
                {
                    ArticleUrl = model.ArticleUrl,
                    Word = wc.Key,
                    Count = wc.Value
                };
                _context.WordCountResults.Add(topWords);
            }
            await _context.SaveChangesAsync();
            // Serialize word count to JSON
            var wordCountJson = JsonConvert.SerializeObject(wordCount);

            model.WordCounts = wordCount;

            return View(model);
        }

        public async Task<string> GetRandomWikipediaArticleUrl()
        {
            var randomPageUrl = "https://en.wikipedia.org/wiki/Special:Random";
            var request = new HttpRequestMessage(HttpMethod.Get, randomPageUrl);
            request.Headers.Add("User-Agent", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3");

            HttpResponseMessage response = await _client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead);
            return response.RequestMessage!.RequestUri!.ToString();
        }

        [HttpGet]
        public async Task<IActionResult> GetRandomWikipediaUrl()
        {
            var randomUrl = await GetRandomWikipediaArticleUrl();
            return Json(new { url = randomUrl });
        }


        private IEnumerable<string> FilterCommonWords(IEnumerable<string> words)
        {
            var commonWordsGerman = new HashSet<string> { "der", "die", "das", "und", "am", "bei", "in", "ist", "zu", "mit", "auf", "für", "ein", "eine", "einer", "nicht", "auch", "sich", "aus", "dem", "den", "im", "als", "wie", "oder", "aber", "dass", "nach", "wenn", "dann", "noch", "über", "vor", "zum", "einen", "zur", "bis", "an", "durch", "um", "von", "haben", "sein", "werden", "kann", "muss", "wird", "sind", "war", "es", "ich", "du", "er", "sie", "es", "wir", "ihr", "sie", "mein", "dein", "sein", "ihr", "unser", "euer", "ihre", "wurde", "vom", "mal", "des", "s", "l", "-" };
            var commonWordsEnglish = new HashSet<string> { "the", "it", "a", "and", "to", "in", "is", "you", "that", "of", "for", "on", "with", "at", "as", "by", "from", "about", "this", "an", "are", "be", "or", "which", "one", "have", "has", "but", "all", "your", "we", "if", "they", "will", "can", "not", "was", "what", "there", "out", "when", "up", "get", "so", "more", "see", "other", "some", "do", "would", "like", "these", "only", "its", "also", "how", "them", "then", "well", "should", "use", "just", "many", "make", "may", "any", "now", "new", "had", "he", "p", "pp", "were", "such", "where", "first", "who", "most", "way", "need", "know", "much", "could", "want", "find", "than", "been", "come", "every", "two", "too", "their", "p.", "iii", "through", "even", "into", "because", "over", "before", "pp.", "go", "work", "between", "must", "our", "after", "think", "best", "each", "never", "under", "right", "going", "own", "around", "still", "look", "might", "provide", "example", "those", "without", "end", "does", "here", "three", "my", "very", "same", "back", "say", "part", "take", "while", "his", "long", "little", "help", "something", "next", "much", "better", "anyone", "always", "though", "off", "us", "given", "last", "let", "great", "being", "less", "several", "away", "thing", "old", "year", "point", "however", "few", "yet", "down", "day", "another", "during", "things", "both", "around", "put", "different", "again", "able", "give", "once", "least", "why", "own", "keep", "done", "called", "number", "ask", "high", "line", "change", "mean", "large", "came", "tell", "group", "become", "important", "every", "include", "became", "run", "life", "order", "course", "fact", "far", "hand", "really", "small", "set", "often", "big", "four", "five", "seem", "felt", "late", "place", "didn't", "someone", "second", "move", "heard", "enough", "took", "person", "got", "nothing" };

            var commonWords = new HashSet<string> { string.Empty };
            commonWords.UnionWith(commonWordsEnglish);
            commonWords.UnionWith(commonWordsGerman);

            return words.Where(word => !commonWords.Contains(word.ToLower())).ToList();
        }
    
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AnotherTechblog</title>    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/layout.css" rel="stylesheet" type="text/css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/dropdown.js"></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AnotherTechblog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                        </li>
                        <li class="nav-item">
                        </li>
                        <li class="nav-item">
                        </li>
                        <li class="nav-item">
                        </li>
                        <li class="nav-item">
                        </li>


                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" id="toolsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Gimmicks
                            </a>

                            <div class="dropdown-menu" aria-labelledby="gimmicksDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Encryption" asp-action="EncryptCipher">Crypto > Encryption</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Decryption" asp-action="DecryptCipher">Crypto > Decryption</a>
                                <a class="dropdown-item" asp-area="" asp-controller="WordCount" asp-action="WordCount">WikiWordCounter</a>
                                @* <a class="dropdown-item" asp-area="" asp-controller="Maze" asp-action="AStarMazeSolver">A* Maze Solver</a>*@
                                <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="CurveSample">Curve Sample</a>
                            </div>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()   
        </main>
    </div>

    <footer class="border-top footer text-muted" style="position: fixed; bottom: 0; left: 0; right: 0;">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="text-center">
                        &copy; 2023 - AnotherTechblog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>